In [2]:
import geopandas as gpd

file_path = "../data/southern-zone.gpkg"

layers = gpd.list_layers(file_path)

layers

                              name geometry_type
0           gis_osm_transport_free         Point
1             gis_osm_traffic_free         Point
2                gis_osm_pois_free         Point
3              gis_osm_places_free         Point
4                gis_osm_pofw_free         Point
5             gis_osm_natural_free         Point
6               gis_osm_roads_free    LineString
7           gis_osm_waterways_free    LineString
8              gis_osm_pois_a_free  MultiPolygon
9           gis_osm_landuse_a_free  MultiPolygon
10           gis_osm_places_a_free  MultiPolygon
11            gis_osm_water_a_free  MultiPolygon
12  gis_osm_protected_areas_a_free  MultiPolygon
13        gis_osm_transport_a_free  MultiPolygon
14       gis_osm_adminareas_a_free  MultiPolygon
15           gis_osm_railways_free    LineString
16          gis_osm_natural_a_free  MultiPolygon
17          gis_osm_traffic_a_free  MultiPolygon
18             gis_osm_pofw_a_free  MultiPolygon
19        gis_osm_buildings_a_free  MultiPolygon

In [4]:
import geopandas as gpd

file_path = "../data/southern-zone.gpkg"

roads = gpd.read_file(
    file_path,
    layer="gis_osm_roads_free"
)

print(roads.shape)
print(roads.columns.tolist())

(3409571, 11)
['osm_id', 'code', 'fclass', 'name', 'ref', 'oneway', 'maxspeed', 'layer', 'bridge', 'tunnel', 'geometry']

In [5]:
roads.head()

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
0,3191425,5122,residential,U2,,B,0,0,F,F,"LINESTRING (76.33477 10.30729, 76.33477 10.306..."
1,3191437,5122,residential,Housing Board,,B,0,0,F,F,"LINESTRING (76.3326 10.29993, 76.33327 10.2998..."
2,3194810,5114,secondary,Market Road,,B,0,0,F,F,"LINESTRING (76.33898 10.30246, 76.33894 10.302..."
3,3195126,5114,secondary,Police Station Road,MDR,B,0,0,F,F,"LINESTRING (76.33727 10.30183, 76.33816 10.301..."
4,3195159,5122,residential,Nirmala College Road,,B,0,0,F,F,"LINESTRING (76.33361 10.29988, 76.33393 10.299..."

In [6]:
roads["ref"].dropna().value_counts().head(50)

ref
           3305735
MDR           6383
NH44          3507
NH16          2945
NH48          2182
NH66          2142
NH65          1395
NH83          1314
ORR           1274
NH544         1234
NH32          1178
NH67          1043
NH150A         950
NH38           948
NH36           931
NH75           854
LR             842
NH71           823
NH50           746
SH1            720
NH81           689
NH163          625
NH52           616
NH216          601
NH40           587
NH69           581
NH183          549
NH648          537
NH85           521
SH234          487
NH73           480
NH167          468
NH42           413
NE7            401
IRR            397
SH59           395
SH15           380
NH948          378
NH365BB        374
NH87           350
SH40           347
NH844          338
NH181          334
NH275          326
NH565          324
NH563          308
SH57           304
SH34           297
SH29           295
SH19           295
Name: count, dtype: int64