In [5]:
import pandas as pd
import numpy as np

df2 = pd.read_csv("../data/table_data D2.csv")

print("shape:", df2.shape)
df2

shape: (37, 12)

,"EV Type (ELECTRIC(BOV), PURE EV), Status (ACTIVE) Wise State Wise and Calendar Year Data for AN, AP, AR, AS, BR, CH, CG, DL, GA, GJ, HR, HP, JK, JH, KA, KL, LA, LD, MP, MH, MN, ML, MZ, NL, OR, PY, PB, RJ, SK, TN, TG, TR, DD, UP, UK, WB (2017-2026)\n\nState",2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,18,2,34,62,12,15,56,146,116,461
1,Andhra Pradesh,0,50,229,91,3827,28395,30545,53652,57389,82596,256774
2,Arunachal Pradesh,0,0,0,2,0,2,15,43,100,133,295
3,Assam,17,61,96,59,409,2517,4634,11836,38308,77685,135622
4,Bihar,8,31,55,97,1803,10418,13646,26766,64330,98932,216086
5,Chandigarh,3,4,7,42,225,1181,3231,3480,3836,4444,16453
6,Chhattisgarh,14,19,35,43,1502,16743,26830,35837,40049,45070,166142
7,Delhi,269,430,765,991,6776,41294,52121,52627,80467,78687,314427
8,Goa,20,7,8,36,794,5582,9314,11360,9309,9519,45949
9,Gujarat,13,36,99,324,6439,67229,85275,72295,73356,91079,396145
10,Haryana,21,47,50,82,2093,12660,10849,24586,25631,29112,105131
11,Himachal Pradesh,1,0,0,100,209,996,1056,1694,1839,1770,7665
12,Jammu and Kashmir,0,3,1,10,434,2437,3852,7281,9436,12551,36005
13,Jharkhand,6,33,54,47,1045,6973,8073,11930,21229,30089,79479
14,Karnataka,224,423,1285,2559,16714,86911,146623,172064,195819,214882,837504
15,Kerala,39,103,181,772,6574,38591,74403,81879,106461,111839,420842
16,Ladakh,0,0,0,0,0,20,0,4,3,7,34
17,Lakshadweep,0,0,0,0,2,2,9,15,29,73,130
18,Madhya Pradesh,9,24,85,69,2504,23014,39128,71262,115057,132308,383460
19,Maharashtra,71,138,539,1527,17927,128382,182013,228417,254471,272132,1085617
20,Manipur,0,0,1,0,9,126,105,184,820,1205,2450
21,Meghalaya,0,0,1,1,3,30,96,302,678,683,1794
22,Mizoram,0,0,0,0,1,36,168,560,825,1000,2590
23,Nagaland,0,1,1,1,0,3,4,12,23,25,70
24,Odisha,4,32,46,74,3109,26287,39949,59658,75873,110826,315858
25,Puducherry,2,6,11,13,202,1447,2567,4348,4484,5708,18788
26,Punjab,12,7,12,14,1679,7625,9537,21642,33335,39381,113244
27,Rajasthan,31,75,150,298,7110,56402,65315,85464,100577,120083,435505
28,Sikkim,0,0,0,0,0,0,0,5,9,11,25
29,Tamil Nadu,22,137,483,1337,15925,64298,83835,124160,158748,206256,655201
30,Telangana,7,88,147,311,4498,31716,47196,70690,83685,95791,334129
31,Tripura,0,2,74,199,234,1001,2568,5800,7303,7284,24465
32,UT of DNH and DD,0,0,0,6,16,111,142,326,291,255,1147
33,Uttar Pradesh,342,689,875,791,5863,30596,62270,132841,227548,306137,767952
34,Uttarakhand,107,196,272,195,1316,7603,8325,11776,15373,19006,64169
35,West Bengal,233,267,690,982,1490,9614,14877,29520,77859,115773,251305
36,Total,1475,2927,6254,11107,110794,710254,1028586,1414372,1884696,2322448,7492913

In [6]:
df2 = df2.rename(columns={df2.columns[0]: "state"})

In [7]:
df2.columns

Index(['state', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024',
       '2025', '2026', 'Total'],
      dtype='str')

In [8]:
southern_states = [
    "Kerala",
    "Karnataka",
    "Tamil Nadu",
    "Telangana",
    "Andhra Pradesh",
    "Puducherry"
]

df2_south = df2[df2["state"].isin(southern_states)].copy()

In [9]:
print("Original Dataset 2:", df2.shape)
print("Southern Dataset 2:", df2_south.shape)

df2_south

Original Dataset 2: (37, 12)
Southern Dataset 2: (6, 12)

,state,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
1,Andhra Pradesh,0,50,229,91,3827,28395,30545,53652,57389,82596,256774
14,Karnataka,224,423,1285,2559,16714,86911,146623,172064,195819,214882,837504
15,Kerala,39,103,181,772,6574,38591,74403,81879,106461,111839,420842
25,Puducherry,2,6,11,13,202,1447,2567,4348,4484,5708,18788
29,Tamil Nadu,22,137,483,1337,15925,64298,83835,124160,158748,206256,655201
30,Telangana,7,88,147,311,4498,31716,47196,70690,83685,95791,334129

In [10]:
df2_south.to_csv(
    "../data/dataset_2_ev_registrations_southern_india.csv",
    index=False
)